### ISSUE TITLE
Using non-public API from syn breaks build when that item goes away in newer version

### ISSUE THREAD

**Issue by zakarumych** [pyros2097/rust-embed#130] opened 2021-01-06 12:18 UTC
This happened already. `syn::export` does not exist in v1.0.58

**Comment by paolobarbolini** [comment] 2021-01-06 12:20
Duplicate of #127, already fixed in #129

**Comment by pyros2097** [comment] 2021-01-06 12:37
Will push a new version now 5.8.0 now.

**Comment by pyros2097** [comment] 2021-01-06 12:42
Done.

**Closed by pyros2097** 2021-01-06 12:42 UTC
